"""Setup configuration for LocoBites Backend."""

from setuptools import setup, find_packages
from pathlib import Path

this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text(encoding="utf-8")

setup(
    name="locco-bites-backend",
    version="1.0.0",
    description="LocoBites - AI-Powered Bakery & Food Ordering Platform Backend",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Ruperth Nyagesoa",
    author_email="ruperthnyagesoa@gmail.com",
    url="https://github.com/locobites/backend",
    project_urls={
        "Documentation": "https://docs.locobites.com",
        "Source": "https://github.com/locobites/backend",
        "Tracker": "https://github.com/locobites/backend/issues",
    },
    packages=find_packages(exclude=["tests", "tests.*", "docs"]),
    python_requires=">=3.11",
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn[standard]>=0.24.0",
        "pydantic>=2.5.0",
        "pydantic-settings>=2.1.0",
        "sqlalchemy>=2.0.23",
        "alembic>=1.12.1",
        "psycopg2-binary>=2.9.9",
        "asyncpg>=0.29.0",
        "redis>=5.0.1",
        "motor>=3.3.2",
        "pymongo>=4.6.0",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-multipart>=0.0.6",
        "email-validator>=2.1.0",
        "python-dotenv>=1.0.0",
        "celery>=5.3.4",
        "flower>=2.0.1",
        "stripe>=7.8.0",
        "twilio>=8.10.0",
        "sendgrid>=6.11.0",
        "boto3>=1.34.0",
        "pillow>=10.1.0",
        "pytz>=2023.3",
        "python-slugify>=8.0.1",
        "requests>=2.31.0",
        "httpx>=0.25.2",
        "websockets>=12.0",
        "aiofiles>=23.2.1",
        "jinja2>=3.1.2",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.3",
            "pytest-asyncio>=0.21.1",
            "pytest-cov>=4.1.0",
            "pytest-mock>=3.12.0",
            "black>=23.11.0",
            "isort>=5.12.0",
            "flake8>=6.1.0",
            "pylint>=3.0.2",
            "mypy>=1.7.1",
            "pre-commit>=3.5.0",
            "bandit>=1.7.5",
            "safety>=2.3.5",
        ],
        "test": [
            "pytest>=7.4.3",
            "pytest-asyncio>=0.21.1",
            "pytest-cov>=4.1.0",
            "pytest-mock>=3.12.0",
            "faker>=20.1.0",
            "factory-boy>=3.3.0",
            "httpx>=0.25.2",
        ],
        "prod": [
            "gunicorn>=21.2.0",
            "gevent>=23.9.1",
        ],
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Framework :: FastAPI",
        "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
        "Topic :: Software Development :: Libraries :: Application Frameworks",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="fastapi bakery food-ordering ai e-commerce api backend",
    include_package_data=True,
    zip_safe=False,
    entry_points={
        "console_scripts": [
            "locobites-server=app.main:main",
        ],
    },
)